# Generated by Django 4.0.6 on 2022-08-10 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uml',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='project',
        ),
        migrations.DeleteModel(
            name='UserTeam',
        ),
        migrations.DeleteModel(
            name='UserUser',
        ),
        migrations.DeleteModel(
            name='UserProject',
        ),
    ]
