# Generated by Django 4.0.6 on 2022-08-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_web', '0002_delete_uml_remove_userproject_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'test1',
                'managed': False,
            },
        ),
    ]
